# Generated by Django 4.2 on 2023-05-03 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='home_address',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
