# Generated by Django 4.2 on 2023-04-18 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_is_deleted_alter_user_deleted_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='location',
            new_name='address',
        ),
    ]
