# Generated by Django 4.2 on 2023-05-03 12:01

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_address_home_address'),
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=255)),
                ('site_area', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('way', django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_site', to='core.project')),
                ('site_location', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.address')),
            ],
        ),
    ]
