# Generated by Django 4.2 on 2023-05-04 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('core', '0003_projectsite_way'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsite',
            name='way',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='way', to='users.address'),
        ),
    ]
