# Generated by Django 4.2 on 2023-04-25 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_document_department_name_project_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='creation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
