# Generated by Django 4.2 on 2023-05-04 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_projectsite_way'),
    ]

    operations = [
        migrations.RenameField(
            model_name='path',
            old_name='site_location',
            new_name='site_loc',
        ),
    ]
