# Generated by Django 4.2 on 2023-04-25 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_department_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
