# Generated by Django 4.2 on 2023-05-08 04:11

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_site_location_path_site_loc'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSiteAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('geom_type', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='projectsite',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectsite',
            name='site_location',
        ),
        migrations.RemoveField(
            model_name='projectsite',
            name='way',
        ),
        migrations.RemoveField(
            model_name='project',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_members',
        ),
        migrations.DeleteModel(
            name='Path',
        ),
        migrations.DeleteModel(
            name='ProjectSite',
        ),
        migrations.AddField(
            model_name='projectsiteaddress',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectsites', to='core.project'),
        ),
    ]
