# Generated by Django 4.2 on 2023-04-26 07:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_alter_document_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_members',
            field=models.ManyToManyField(related_name='people_involved', to=settings.AUTH_USER_MODEL),
        ),
    ]
