# Generated by Django 4.2 on 2023-04-28 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_project_project_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummaryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('total_projects', models.IntegerField()),
                ('total_users', models.IntegerField()),
            ],
        ),
    ]
