# Generated by Django 4.2 on 2023-04-28 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_summarydata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summarydata',
            name='total_projects',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
