# Generated by Django 4.2 on 2023-05-08 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_projectsiteaddress_geom_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsiteaddress',
            name='area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectsiteaddress',
            name='geom_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
