# Generated by Django 4.2 on 2023-04-17 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='project',
            table='PROJECT',
        ),
    ]
