# Generated by Django 4.2 on 2023-04-17 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_project_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='project',
            table='project',
        ),
    ]
