# Generated by Django 4.2 on 2023-04-18 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_project_start_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='joined_date',
            new_name='creation_date',
        ),
    ]
