# Generated by Django 4.2 on 2023-04-18 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_joined_date_department_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='creation_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
