# Generated by Django 4.2 on 2023-04-18 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_department_creation_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='additional_docs/')),
                ('additional_documents', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.document')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='additional_docs',
            field=models.ManyToManyField(blank=True, to='api.additionaldoc'),
        ),
    ]
