# Generated by Django 4.2 on 2023-04-18 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_additionaldoc_document_additional_docs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='creation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
