# Generated by Django 4.2 on 2023-04-18 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_department_creation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='additional_docs',
        ),
    ]
