# Generated by Django 4.2 on 2023-04-19 05:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0011_userinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='departments',
            field=models.ManyToManyField(blank=True, to='api.department'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='documents',
            field=models.ManyToManyField(blank=True, to='api.document'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='projects',
            field=models.ManyToManyField(blank=True, to='api.project'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_info', to=settings.AUTH_USER_MODEL),
        ),
    ]
