# Generated by Django 4.2 on 2023-04-19 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_document_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='created_by',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
