# Generated by Django 4.2 on 2023-04-21 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_document_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='created_by',
        ),
    ]
