# Generated by Django 4.2 on 2023-04-24 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_userinfo_departments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='department',
        ),
    ]
