# Generated by Django 4.2 on 2023-04-24 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_userinfo_departments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='departments',
        ),
    ]
