# Generated by Django 4.2 on 2023-04-24 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_document_added_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='added_by',
        ),
    ]
