# Generated by Django 4.2 on 2023-04-25 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userprofile_location'),
        ('api', '0026_document_document_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='documents',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_added', to='api.document'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='user_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_info', to='users.userprofile'),
        ),
        migrations.AlterField(
            model_name='department',
            name='creation_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
